/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface WalletInterface extends ethers.utils.Interface {
  functions: {
    "ERC721_RECEIVED()": FunctionFragment;
    "call(address,uint256,bytes,uint8,uint256)": FunctionFragment;
    "contractFactory()": FunctionFragment;
    "initialize(address,address,uint256)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "selfContractAddress()": FunctionFragment;
    "selfTokenId()": FunctionFragment;
    "sendERC20(address,address,uint256)": FunctionFragment;
    "sendERC721(address,address,uint256)": FunctionFragment;
    "sendEth(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ERC721_RECEIVED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "call",
    values: [string, BigNumberish, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "selfContractAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selfTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendERC20",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendERC721",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendEth",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ERC721_RECEIVED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "call", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selfTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendERC20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendERC721", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendEth", data: BytesLike): Result;

  events: {
    "CallExecuted(address,uint256,bytes,uint8,uint256)": EventFragment;
    "ERC20Transfered(address,address,uint256)": EventFragment;
    "ERC721Transfered(address,address,uint256)": EventFragment;
    "ETHTransfered(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CallExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC20Transfered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ERC721Transfered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ETHTransfered"): EventFragment;
}

export type CallExecutedEvent = TypedEvent<
  [string, BigNumber, string, number, BigNumber],
  {
    target: string;
    value: BigNumber;
    data: string;
    operation: number;
    gas: BigNumber;
  }
>;

export type CallExecutedEventFilter = TypedEventFilter<CallExecutedEvent>;

export type ERC20TransferedEvent = TypedEvent<
  [string, string, BigNumber],
  { token: string; recipient: string; amount: BigNumber }
>;

export type ERC20TransferedEventFilter = TypedEventFilter<ERC20TransferedEvent>;

export type ERC721TransferedEvent = TypedEvent<
  [string, string, BigNumber],
  { token: string; recipient: string; amount: BigNumber }
>;

export type ERC721TransferedEventFilter =
  TypedEventFilter<ERC721TransferedEvent>;

export type ETHTransferedEvent = TypedEvent<
  [string, BigNumber],
  { recipient: string; amount: BigNumber }
>;

export type ETHTransferedEventFilter = TypedEventFilter<ETHTransferedEvent>;

export interface Wallet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WalletInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ERC721_RECEIVED(overrides?: CallOverrides): Promise<[string]>;

    call(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      txGas: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    contractFactory(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _contractFactory: string,
      _contractAddress: string,
      _tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    selfContractAddress(overrides?: CallOverrides): Promise<[string]>;

    selfTokenId(overrides?: CallOverrides): Promise<[BigNumber]>;

    sendERC20(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendERC721(
      token: string,
      recipient: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendEth(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ERC721_RECEIVED(overrides?: CallOverrides): Promise<string>;

  call(
    target: string,
    value: BigNumberish,
    data: BytesLike,
    operation: BigNumberish,
    txGas: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  contractFactory(overrides?: CallOverrides): Promise<string>;

  initialize(
    _contractFactory: string,
    _contractAddress: string,
    _tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  selfContractAddress(overrides?: CallOverrides): Promise<string>;

  selfTokenId(overrides?: CallOverrides): Promise<BigNumber>;

  sendERC20(
    token: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendERC721(
    token: string,
    recipient: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendEth(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ERC721_RECEIVED(overrides?: CallOverrides): Promise<string>;

    call(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      txGas: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    contractFactory(overrides?: CallOverrides): Promise<string>;

    initialize(
      _contractFactory: string,
      _contractAddress: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    selfContractAddress(overrides?: CallOverrides): Promise<string>;

    selfTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    sendERC20(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sendERC721(
      token: string,
      recipient: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sendEth(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CallExecuted(address,uint256,bytes,uint8,uint256)"(
      target?: string | null,
      value?: null,
      data?: null,
      operation?: null,
      gas?: null
    ): CallExecutedEventFilter;
    CallExecuted(
      target?: string | null,
      value?: null,
      data?: null,
      operation?: null,
      gas?: null
    ): CallExecutedEventFilter;

    "ERC20Transfered(address,address,uint256)"(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): ERC20TransferedEventFilter;
    ERC20Transfered(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): ERC20TransferedEventFilter;

    "ERC721Transfered(address,address,uint256)"(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): ERC721TransferedEventFilter;
    ERC721Transfered(
      token?: string | null,
      recipient?: string | null,
      amount?: null
    ): ERC721TransferedEventFilter;

    "ETHTransfered(address,uint256)"(
      recipient?: string | null,
      amount?: null
    ): ETHTransferedEventFilter;
    ETHTransfered(
      recipient?: string | null,
      amount?: null
    ): ETHTransferedEventFilter;
  };

  estimateGas: {
    ERC721_RECEIVED(overrides?: CallOverrides): Promise<BigNumber>;

    call(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      txGas: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    contractFactory(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _contractFactory: string,
      _contractAddress: string,
      _tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    selfContractAddress(overrides?: CallOverrides): Promise<BigNumber>;

    selfTokenId(overrides?: CallOverrides): Promise<BigNumber>;

    sendERC20(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendERC721(
      token: string,
      recipient: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendEth(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ERC721_RECEIVED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    call(
      target: string,
      value: BigNumberish,
      data: BytesLike,
      operation: BigNumberish,
      txGas: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    contractFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _contractFactory: string,
      _contractAddress: string,
      _tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    selfContractAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    selfTokenId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendERC20(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendERC721(
      token: string,
      recipient: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendEth(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
