/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { I721, I721Interface } from "../I721";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class I721__factory {
  static readonly abi = _abi;
  static createInterface(): I721Interface {
    return new utils.Interface(_abi) as I721Interface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): I721 {
    return new Contract(address, _abi, signerOrProvider) as I721;
  }
}
