/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWallet, IWalletInterface } from "../IWallet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "contractFactory",
        type: "address",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "receive",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IWallet__factory {
  static readonly abi = _abi;
  static createInterface(): IWalletInterface {
    return new utils.Interface(_abi) as IWalletInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWallet {
    return new Contract(address, _abi, signerOrProvider) as IWallet;
  }
}
